# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ml_S', '0002_auto_20181030_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=600),
        ),
    ]
