# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ml_S', '0004_auto_20181030_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headImg', models.CharField(max_length=600)),
                ('name', models.CharField(max_length=300)),
                ('prince', models.IntegerField()),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
    ]
