# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ml_S', '0006_wheel1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=256),
        ),
    ]
