# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ml_S', '0007_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='ltilep',
            field=models.CharField(default='', max_length=100),
        ),
    ]
