# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ml_S', '0008_goods_ltilep'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='wheel1',
            table='wheel',
        ),
    ]
