# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-05 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ml_S', '0009_auto_20181102_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='headImg',
            new_name='headIng',
        ),
    ]
