# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ml_S', '0010_auto_20181105_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ml_S.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ml_S.User')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
