# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ml_S', '0011_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='introduction',
            field=models.CharField(default='good', max_length=600),
        ),
    ]
